### ISSUE TITLE
I don't understand what the `--crit` and `--warn` flags are supposed to do

### ISSUE THREAD

**Issue by aayore** [sensu-plugins/sensu-plugins-logs#13]
I don't know how to interpret "Critical/Warning level if pattern has a group."

It seems like `--crit N` would only trigger a critical event if the check found N or more matching lines.
It seems like `--warn-only --warn N` would trigger a warning event if the check found N or more matching lines.

These don't work for me as expected, and don't seem relevant to the code at all.  Was a breaking change in Ruby that's affecting this?  I'm using Ruby 2.3.1, and it seems like it's impossible to get in to the `if m[1]` clause at https://github.com/sensu-plugins/sensu-plugins-logs/blob/master/bin/check-log.rb#L192.

If I'm misunderstanding the intended use of `--crit` and `--warn`, what are they intended to do?

If my interpretation is correct, I'm happy to submit a PR to update them (it's pretty much ready to go).  But I worry that it could be a breaking change for existing implementations.

**Comment by majormoses** [comment]
I have not used this plugin but what you describe sounds rationale given the common pattern and name of options. I would be happy to look at a PR to evaluate if it breaks intended use cases.

**Comment by avifried1** [comment]
following pull request addresses this: 
https://github.com/sensu-plugins/sensu-plugins-logs/pull/24

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-logs/versions/1.1.1

**Comment by cgeers** [comment]
@majormoses 
#24 ended up being backwards incompatible in two ways:

1) The original use case of `crit` and `warn` applying only to a numeric value in a capture group was removed.
2) there was an implicit critical severity that would be returned if any matches occured at least once. 

That said, IMHO the current behavior is actually more reasonable than the previous. I have create #33 to correct the documentation

**Comment by majormoses** [comment]
@cgeers ouch and thanks for the assist.

EDIT: after reviewing it more we are gonna have to just go forward as there is too much effort involved in ensuring that we retroactively fix it. I have left some comments and after they are addressed we can merge and release a fix.

**Comment by aayore** [comment]
Sorry I lost track of this.  Thank you for following up on it.

**Comment by cgeers** [comment]
@majormoses Sounds good. I'll push the requested changes ASAP.
