### ISSUE TITLE
New release and new gem

### ISSUE THREAD

**Issue by vadim6** [sensu-plugins/sensu-plugins-logs#17]
Hi,
When is a new release planned for the plugin? Since the last release on March 12 2016 there have been a couple of fixes made to the plugin.
I install all plugins as gems on my servers, is there some better way to get the latest fixes other than waiting for new gem to be released?

**Comment by eheydrick** [comment]
Hello, I just released 1.0.0.

**Comment by vadim6** [comment]
Thank you!
