### ISSUE TITLE
Large output returned from the plugin causing sensu server to hang

### ISSUE THREAD

**Issue by jhshadi** [sensu-plugins/sensu-plugins-logs#28]
We encounter some issue when a large amount of errors has been written to the log and the `--return` flag is set all. the matched errors in the log are collected and sent in the response body sent to the sensu server. few times we encounter a very large response that caused the sensu server to hang.

We might want to implement an option to limit the number of errors in order to avoid large output sent to the sensu server.

**Comment by majormoses** [comment]
I have not taken enough of a look at the code as I need to run out shortly but it feels like you might be able to do this with: https://github.com/sensu-plugins/sensu-plugins-logs/blob/1.2.0/bin/check-log.rb#L124

**Comment by jhshadi** [comment]
@majormoses not quite. this option limit the length of returned line\log entry.
but let's say 1000000 matched lines will be written to the log, the plugin will collect all of those lines\log entries in the returned output, which can be accumulated to a very large output.

i have created a PR with the option to limit the number of matched lines\log entries in order to have more control over the returned output size sent back to the sensu server.

**Comment by majormoses** [comment]
I see, would it be better to maybe worry about say the number of bytes vs number of lines returned as a really long line could cause the same crashes.

**Comment by jhshadi** [comment]
@majormoses combining the `return-length` option with `return-error-limit` option you can control the precise number of bytes to return.

**Comment by majormoses** [comment]
ah hah so we did add, perfect.

**Comment by majormoses** [comment]
closed via #29
