### ISSUE TITLE
Compatibility with CentOS?

### ISSUE THREAD

**Issue by asc-zgreen** [sensu-plugins/sensu-plugins-logs#82]
I've installed sensu-plugins-logs as a Sensu Go asset via Bonsai, and I've hit a bit of a snag with running checks on our CentOS systems, namely that they don't pick up the asset.

It looks like this is because the filter expression in the asset definition is checking entity.system.platform for the value 'rhel', but this key contains 'centos' on the systems in question. I've noticed that most of the other plugins we're using are checking entity.system.platform_family, which does contain 'rhel'.

Is this by design because of a compatibility issue, or is this something that could potentially be changed?

Versions of things: CentOS 7.7, Sensu Go 5.18.1, sensu-plugins-logs 4.0.0

**Comment by nixwiz** [comment]
The fix for using platform_family has already been made to the repo, we've just not rolled a new release/bonsai asset.  We will try to address that soon.

**Comment by asc-zgreen** [comment]
Awesome, thanks!
